# This is a basic workflow to help you get started with Actions

name: workflow2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #repository_dispatch:
  #  types: [ my-event ]
    


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
        #  ref: ${{ github.event.client_payload.ref }}
        

      #- name: Build docker file
      #  run: |
      #    docker build . -t neocycf/test-image:${{ github.sha }}
      #    docker images --digests
          
      - run: |
          curl -i -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/repos
      #    echo ${{ github.event.client_payload.sha }}
      #    echo ${{ secrets.GITHUB_TOKEN }} >> temp.txt
      #    cat temp.txt
      #    pwd
      #    ls -lrt

      - name: Update Image Version in the related HelmChart values.yaml
        #uses: fjogeleit/yaml-update-action@master
        uses: neocycf/yaml-update-action@eaf7a167cee9e36496050edff9b8490a43061054
        with:
          valueFile: 'helm/github-actions-runner/values.yaml'
          propertyPath: 'replicaCount'
          value: 1 #${{ github.sha }}
          branch: "my-branch"
          #targetBranch: main
          createPR: False
          message: 'Update Image Version'
          token: ${{ secrets.GITHUB_TOKEN }}
          updateFile: True

      
