# This is a basic workflow to help you get started with Actions

name: workflow2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  repository_dispatch:
    types: [ my-event ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Build docker file
        run: |
          docker build . -t neocycf/test-image:${{ github.sha }}
      
      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'helm/github-actions-runner/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ github.sha }}
          branch: deployment/${{ github.sha }}
          targetBranch: master
          createPR: 'true'
          message: 'Update Image Version to ${{ github.sha }}'
          labels: |
            automated pr

      - run: echo ${{ github.event.client_payload.sha }}
